---
- name: Deploy Flask Docker Application
  hosts: all
  become: yes

  vars:
    app_dir: /home/leeshalulu/flask-docker-app
    container_name: flask-app
    image_name: my-flask-app
    docker_image_tag: "latest"

  tasks:
    - name: Install Docker on Debian/Ubuntu
      apt:
        name:
          - docker.io
          - python3-docker
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Docker on RHEL based systems
      dnf:
        name:
          - docker
          - python3-docker
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: leeshalulu
        group: leeshalulu
        mode: '0755'

    - name: Copy application files
      copy:
        src: "{{ item }}"
        dest: "{{ app_dir }}/{{ item }}"
        owner: leeshalulu
        group: leeshalulu
      loop:
        - app.py
        - requirements.txt
        - Dockerfile

    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ docker_image_tag }}"
        source: build
        build:
          path: "{{ app_dir }}"

    - name: Stop and remove existing container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent

    - name: Run Docker container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}:{{ docker_image_tag }}"
        state: started
        restart_policy: always
        ports:
          - "5000:5000"

    - name: Verify container is running
      community.docker.docker_container_info:
        name: "{{ container_name }}"
      register: container_info

    - name: Check application health
      uri:
        url: "http://localhost:5000"
        method: GET
        status_code: 200
        timeout: 30
      register: health_check
      until: health_check.status == 200
      retries: 5
      delay: 5

