---
- name: Deploy Dockerized Flask App
  hosts: all
  become: yes
  tasks:
    - name: Create application directory on target
      ansible.builtin.file:
        path: /home/ec2-user/docker-flask-app
        state: directory
        owner: ec2-user
        group: ec2-user

    - name: Copy application files to target
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/ec2-user/docker-flask-app/
        owner: ec2-user
        group: ec2-user
      loop:
        - app.py
        - requirements.txt
        - Dockerfile

    - name: Build Docker image
      community.docker.docker_image:
        name: my-flask-app
        source: build
        build:
          path: /home/ec2-user/docker-flask-app
        force_source: yes

    - name: Run Docker container
      community.docker.docker_container:
        name: flask-app
        image: my-flask-app
        state: started
        restart: yes
        ports:
          - "5000:5000"
        detach: yes
